### ISSUE TITLE
Duplicate case value in cpr/error.cpp causes failure to build

### ISSUE THREAD

**Issue by A-M-Simmons** [karnival/cpp-opencage-geocoder#2]
Error during make process. Specifically, duplicate case of CURLE_SSL_CACERT and CURLE_PEER_FAILED_VERIFICATION.

```
/home/alex/cpp-opencage-geocoder/cpr/cpr/error.cpp:41:9: error: duplicate case value
         case CURLE_SSL_CACERT:
         ^~~~
/home/alex/cpp-opencage-geocoder/cpr/cpr/error.cpp:25:9: note: previously used here
         case CURLE_PEER_FAILED_VERIFICATION:
         ^~~~
```

Resolution found on the cpr issues page works for me [link](https://github.com/whoshuu/cpr/pull/296#issuecomment-451352317).

(Apologies if poor formatting, first ever issue post).

**Comment by karnival** [comment]
Thanks for raising this, and good job on the first issue post.

If you're interested in getting your first PR, feel free to submit a PR with that fix and I'll help guide it through. Otherwise I'll fix this in the next couple of days.

**Comment by karnival** [comment]
I've pulled in changes from the upstream cpr repo and updated this project's cpr subtree accordingly.

@A-M-Simmons could you check that `master` now builds fine? I wasn't able to reproduce the original issue, which I guess is platform-dependent.
